/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";

export class UpdateOrderActionRequest extends SpeakeasyBase {
    /**
     * Order
     */
    @SpeakeasyMetadata({ data: "request, media_type=application/json" })
    order: shared.Order;

    /**
     * ID of order to delete
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=orderId" })
    orderId: number;
}

export class UpdateOrderActionResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    contentType: string;

    /**
     * unexpected error
     */
    @SpeakeasyMetadata()
    error?: shared.ErrorT;

    /**
     * Order Response
     */
    @SpeakeasyMetadata()
    order?: shared.Order;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;
}
